"""initial_schema

Revision ID: 5b73bff49bcf
Revises: 
Create Date: 2026-04-15 22:03:22.793818

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b73bff49bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('graph_attachment_id', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_inline', sa.Boolean(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("source_type IN ('email','chat_message')", name='ck_attachments_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_active', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_cache',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('head_id', sa.Integer(), nullable=True),
    sa.Column('parent_dept_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("source IN ('inferred','manual','teams')", name='ck_departments_source'),
    sa.ForeignKeyConstraint(['head_id'], ['people.id'], use_alter=True),
    sa.ForeignKeyConstraint(['parent_dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'model', 'task', name='uq_llm_usage_daily')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transcript_status', sa.String(), nullable=True),
    sa.Column('meeting_type', sa.String(), nullable=True),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('calendar_event_id', sa.Text(), nullable=True),
    sa.Column('online_meeting_url', sa.Text(), nullable=True),
    sa.Column('recurring_series_id', sa.Text(), nullable=True),
    sa.Column('instance_number', sa.Integer(), nullable=True),
    sa.Column('organizer_email', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('screen_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("meeting_type IN ('virtual','in_person','hybrid','solo_block')", name='ck_meetings_type'),
    sa.CheckConstraint("processing_status IN ('pending','processing','completed','failed')", name='ck_meetings_processing_status'),
    sa.CheckConstraint("sentiment IN ('positive','neutral','tense','negative','urgent')", name='ck_meetings_sentiment'),
    sa.CheckConstraint("status IN ('scheduled','in_progress','completed')", name='ck_meetings_status'),
    sa.CheckConstraint("transcript_status IN ('pending','captured','partial','no_audio','processing','failed')", name='ck_meetings_transcript_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id')
    )
    op.create_index('idx_meetings_calendar_event', 'meetings', ['calendar_event_id'], unique=False)
    op.create_index('idx_meetings_series', 'meetings', ['recurring_series_id'], unique=False)
    op.create_index('idx_meetings_start', 'meetings', ['start_time'], unique=False)
    op.create_table('sentiment_aggregations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("scope_type IN ('person','relationship','department','cross_department','workstream')", name='ck_sentiment_scope_type'),
    sa.CheckConstraint("trend IN ('up','down','flat')", name='ck_sentiment_trend'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', 'period_start', name='uq_sentiment_scope')
    )
    op.create_table('system_health',
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('last_success', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('items_processed_last_hour', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('healthy','degraded','down')", name='ck_system_health_status'),
    sa.PrimaryKeyConstraint('service')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_team_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_team_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('voice_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_profile', sa.Text(), nullable=True),
    sa.Column('custom_rules', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('edit_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_learned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_type', sa.String(), nullable=False),
    sa.Column('related_meeting_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("briefing_type IN ('morning','monday','friday','meeting_prep')", name='ck_briefings_type'),
    sa.ForeignKeyConstraint(['related_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_topics',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'topic_id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('org', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('first_seen', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('cc_gravity_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('llm_suggestion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("seniority IN ('executive','senior','mid','junior','unknown')", name='ck_people_seniority'),
    sa.CheckConstraint("source IN ('calendar','email','teams','meeting','manual','backfill')", name='ck_people_source'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_people_department', 'people', ['department_id'], unique=False)
    op.create_index('idx_people_email', 'people', ['email'], unique=False)
    op.create_table('team_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_channel_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_channel_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_message_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('thread_root_id', sa.Text(), nullable=True),
    sa.Column('linked_meeting_id', sa.Integer(), nullable=True),
    sa.Column('noise_filtered', sa.Boolean(), nullable=False),
    sa.Column('triage_class', sa.String(), nullable=True),
    sa.Column('triage_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("intent IN ('request','fyi','decision_needed','follow_up','question','response')", name='ck_chat_messages_intent'),
    sa.CheckConstraint("processing_status IN ('pending','processing','completed','failed')", name='ck_chat_messages_processing_status'),
    sa.CheckConstraint("sentiment IN ('positive','neutral','tense','negative','urgent')", name='ck_chat_messages_sentiment'),
    sa.CheckConstraint("source_type IN ('teams_chat','teams_channel')", name='ck_chat_messages_source'),
    sa.CheckConstraint("triage_class IN ('substantive','contextual','noise')", name='ck_chat_messages_triage'),
    sa.ForeignKeyConstraint(['channel_id'], ['team_channels.id'], ),
    sa.ForeignKeyConstraint(['linked_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_message_id')
    )
    op.create_index('idx_chat_messages_datetime', 'chat_messages', ['datetime'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('triggered_by_type', sa.String(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=True),
    sa.Column('chat_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('email','teams_chat')", name='ck_drafts_channel'),
    sa.CheckConstraint("draft_type IN ('nudge','recap','response','follow_up')", name='ck_drafts_type'),
    sa.CheckConstraint("status IN ('pending_review','sent','discarded','edited')", name='ck_drafts_status'),
    sa.CheckConstraint("triggered_by_type IN ('action_item','email_ask','chat_ask','meeting')", name='ck_drafts_triggered_by'),
    sa.ForeignKeyConstraint(['recipient_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graph_id', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('importance', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('email_class', sa.String(), nullable=True),
    sa.Column('triage_class', sa.String(), nullable=True),
    sa.Column('triage_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=True),
    sa.Column('response_status', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_extracted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("email_class IN ('human','automated','newsletter')", name='ck_emails_class'),
    sa.CheckConstraint("intent IN ('request','fyi','decision_needed','follow_up','question','response','scheduling')", name='ck_emails_intent'),
    sa.CheckConstraint("processing_status IN ('pending','processing','completed','failed')", name='ck_emails_processing_status'),
    sa.CheckConstraint("response_status IN ('pending','replied','no_action_needed','overdue')", name='ck_emails_response_status'),
    sa.CheckConstraint("sentiment IN ('positive','neutral','tense','negative','urgent')", name='ck_emails_sentiment'),
    sa.CheckConstraint("triage_class IN ('substantive','contextual','noise')", name='ck_emails_triage'),
    sa.ForeignKeyConstraint(['sender_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_id')
    )
    op.create_index('idx_emails_datetime', 'emails', ['datetime'], unique=False)
    op.create_index('idx_emails_sender', 'emails', ['sender_id'], unique=False)
    op.create_index('idx_emails_thread', 'emails', ['thread_id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'person_id')
    )
    op.create_table('people_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('change_source', sa.String(), nullable=True),
    sa.CheckConstraint("change_source IN ('inferred','manual')", name='ck_people_history_source'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_memberships',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'person_id')
    )
    op.create_table('workstreams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('auto_quiet_days', sa.Integer(), nullable=False),
    sa.Column('split_from_id', sa.Integer(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("created_by IN ('auto','manual')", name='ck_workstreams_created_by'),
    sa.CheckConstraint("status IN ('active','quiet','paused','completed','archived')", name='ck_workstreams_status'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['workstreams.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['split_from_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('source_meeting_id', sa.Integer(), nullable=True),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('source_chat_message_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("status IN ('open','in_progress','completed','stale')", name='ck_action_items_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['source_chat_message_id'], ['chat_messages.id'], use_alter=True),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['source_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_items_assignee', 'action_items', ['assignee_id'], unique=False)
    op.create_index('idx_action_items_status', 'action_items', ['status'], unique=False)
    op.create_table('chat_message_topics',
    sa.Column('chat_message_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('chat_message_id', 'topic_id')
    )
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('committer_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('source_meeting_id', sa.Integer(), nullable=True),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('open','completed','overdue','broken')", name='ck_commitments_status'),
    sa.ForeignKeyConstraint(['committer_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['source_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('source_meeting_id', sa.Integer(), nullable=True),
    sa.Column('source_email_id', sa.Integer(), nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['people.id'], ),
    sa.ForeignKeyConstraint(['source_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['source_meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_workstream_id', sa.Integer(), nullable=True),
    sa.Column('blocked_workstream_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('identified_date', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('active','resolved')", name='ck_dependencies_status'),
    sa.ForeignKeyConstraint(['blocked_workstream_id'], ['workstreams.id'], ),
    sa.ForeignKeyConstraint(['blocker_workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_topics',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'topic_id')
    )
    op.create_table('workstream_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workstream_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('linked_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('linked_by', sa.String(), nullable=True),
    sa.CheckConstraint("item_type IN ('meeting','email','chat_message','action_item','decision','commitment','email_ask','chat_ask')", name='ck_workstream_items_type'),
    sa.CheckConstraint("linked_by IN ('auto','manual')", name='ck_workstream_items_linked_by'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workstream_id', 'item_type', 'item_id', name='uq_workstream_item')
    )
    op.create_index('idx_workstream_items_item', 'workstream_items', ['item_type', 'item_id'], unique=False)
    op.create_index('idx_workstream_items_ws', 'workstream_items', ['workstream_id'], unique=False)
    op.create_table('workstream_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workstream_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("status IN ('pending','in_progress','completed')", name='ck_workstream_milestones_status'),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workstream_stakeholders',
    sa.Column('workstream_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.CheckConstraint("role IN ('owner','lead','contributor','informed')", name='ck_workstream_stakeholders_role'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['workstream_id'], ['workstreams.id'], ),
    sa.PrimaryKeyConstraint('workstream_id', 'person_id')
    )
    op.create_table('chat_asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('ask_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolved_by_message_id', sa.Integer(), nullable=True),
    sa.Column('linked_action_item_id', sa.Integer(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("ask_type IN ('deliverable','decision','follow_up','question','approval','review','info_request')", name='ck_chat_asks_type'),
    sa.CheckConstraint("status IN ('open','in_progress','completed','stale')", name='ck_chat_asks_status'),
    sa.CheckConstraint("urgency IN ('high','medium','low')", name='ck_chat_asks_urgency'),
    sa.ForeignKeyConstraint(['linked_action_item_id'], ['action_items.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_asks_status', 'chat_asks', ['status'], unique=False)
    op.create_table('email_asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('ask_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resolved_by_email_id', sa.Integer(), nullable=True),
    sa.Column('linked_action_item_id', sa.Integer(), nullable=True),
    sa.Column('linked_meeting_id', sa.Integer(), nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.CheckConstraint("ask_type IN ('deliverable','decision','follow_up','question','approval','review','info_request')", name='ck_email_asks_type'),
    sa.CheckConstraint("status IN ('open','in_progress','completed','stale')", name='ck_email_asks_status'),
    sa.CheckConstraint("urgency IN ('high','medium','low')", name='ck_email_asks_urgency'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['linked_action_item_id'], ['action_items.id'], ),
    sa.ForeignKeyConstraint(['linked_meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_asks_status', 'email_asks', ['status'], unique=False)
    op.create_index('idx_email_asks_target', 'email_asks', ['target_id'], unique=False)

    # HNSW vector indexes
    op.execute("CREATE INDEX idx_meetings_embedding ON meetings USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_emails_embedding ON emails USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_chat_messages_embedding ON chat_messages USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_action_items_embedding ON action_items USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_email_asks_embedding ON email_asks USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_workstreams_embedding ON workstreams USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_topics_embedding ON topics USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop HNSW vector indexes
    op.execute("DROP INDEX IF EXISTS idx_topics_embedding")
    op.execute("DROP INDEX IF EXISTS idx_workstreams_embedding")
    op.execute("DROP INDEX IF EXISTS idx_email_asks_embedding")
    op.execute("DROP INDEX IF EXISTS idx_action_items_embedding")
    op.execute("DROP INDEX IF EXISTS idx_chat_messages_embedding")
    op.execute("DROP INDEX IF EXISTS idx_emails_embedding")
    op.execute("DROP INDEX IF EXISTS idx_meetings_embedding")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email_asks_target', table_name='email_asks')
    op.drop_index('idx_email_asks_status', table_name='email_asks')
    op.drop_table('email_asks')
    op.drop_index('idx_chat_asks_status', table_name='chat_asks')
    op.drop_table('chat_asks')
    op.drop_table('workstream_stakeholders')
    op.drop_table('workstream_milestones')
    op.drop_index('idx_workstream_items_ws', table_name='workstream_items')
    op.drop_index('idx_workstream_items_item', table_name='workstream_items')
    op.drop_table('workstream_items')
    op.drop_table('email_topics')
    op.drop_table('dependencies')
    op.drop_table('decisions')
    op.drop_table('commitments')
    op.drop_table('chat_message_topics')
    op.drop_index('idx_action_items_status', table_name='action_items')
    op.drop_index('idx_action_items_assignee', table_name='action_items')
    op.drop_table('action_items')
    op.drop_table('workstreams')
    op.drop_table('team_memberships')
    op.drop_table('people_history')
    op.drop_table('meeting_attendees')
    op.drop_index('idx_emails_thread', table_name='emails')
    op.drop_index('idx_emails_sender', table_name='emails')
    op.drop_index('idx_emails_datetime', table_name='emails')
    op.drop_table('emails')
    op.drop_table('drafts')
    op.drop_index('idx_chat_messages_datetime', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('team_channels')
    op.drop_index('idx_people_email', table_name='people')
    op.drop_index('idx_people_department', table_name='people')
    op.drop_table('people')
    op.drop_table('meeting_topics')
    op.drop_table('briefings')
    op.drop_table('voice_profile')
    op.drop_table('topics')
    op.drop_table('teams')
    op.drop_table('system_health')
    op.drop_table('sentiment_aggregations')
    op.drop_index('idx_meetings_start', table_name='meetings')
    op.drop_index('idx_meetings_series', table_name='meetings')
    op.drop_index('idx_meetings_calendar_event', table_name='meetings')
    op.drop_table('meetings')
    op.drop_table('llm_usage')
    op.drop_table('departments')
    op.drop_table('dashboard_cache')
    op.drop_table('chat_sessions')
    op.drop_table('attachments')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
